//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessBudget.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenDirectory {
            get {
                return ((string)(this["OpenDirectory"]));
            }
            set {
                this["OpenDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirectory {
            get {
                return ((string)(this["SaveDirectory"]));
            }
            set {
                this["SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Mortgage, 839.65, AutoFill;HOA, 384, AutoFill;Gas, 80, Budgeted;Car Payment, 325.03, AutoFill;Auto Insurance, 239.33, AutoFill;Internet, 80, AutoFill;Phone, 75, AutoFill;Groceries, 400, BudgetedDecrement;Pet Groceries, 100, BudgetedDecrement;Electricity, 180, FillIfNotPresent;Gym, 72.42, AutoFill;Entertainment, 26.67, AutoFill;Dues, 15, AutoFill")]
        public string BudgetCategories {
            get {
                return ((string)(this["BudgetCategories"]));
            }
            set {
                this["BudgetCategories"] = value;
            }
        }
    }
}
